-- AlterTable
ALTER TABLE "data" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "skills" SET NOT NULL,
ALTER COLUMN "skills" SET DATA TYPE TEXT,
ALTER COLUMN "completed_projects" SET NOT NULL,
ALTER COLUMN "completed_projects" SET DATA TYPE TEXT;
